name: Validacion de pruebas pre-merge
on:
  push:
    branches: ['feature**', 'hotfix**']
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'FINALIZADO') }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.10.4'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v tests/test_logica_en_forma.py
    - name: Cálculo de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest tests/test_logica_en_forma.py
          coverage report -m
    - name: Validar resultados previos con errores
      if: ${{ failure() }}
      run: echo "Una o varias pruebas fallaron"
    - name: Merge con develop
      if: ${{ success() }}
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: develop
        target-branch: ${{ github.ref }}